games_on_rails/config/routes.rb
GamingApp::Application.routes.draw do
  root "games#index"

  resources :secret_numbers, :only => [:new, :show]

  resources :rock_paper_scissors, :only => [:new, :show]

  get '/games', to: 'games#index'

  get '/secret_numbers', to: 'secret_numbers#new'

end

games_on_rails/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

games_on_rails/app/controllers/rock_paper_scissors_controller.rb
# secret_numbers_controller.rb

class RockPaperScissorsController < ApplicationController
  
  def new
  	@throw = get_throw
  end

  def get_throw
  	['rock', 'paper' ,'scissors']
  end 


  def show
  	@throw = get_throw
  	@user_throw = @throw[params[:id].to_i]
  	@comp_throw = @throw[rand(2)]
  	@status = ""
  end

  def result(comp_throw, user_throw)
  	if user_throw == "rock" && @comp_throw == "scissors"
  		@status = :win
  	elsif user_throw == "paper" && @comp_throw == "rock"
  		@status = :win
  	elsif user_throw == "scissors" && @comp_throw == "paper"
  		@status = :win
  	elsif user_throw == "scissors" && @comp_throw == "rock"
  		@status = :lose
  	elsif user_throw == "rock" && @comp_throw == "paper"
  		@status = :lose
  	elsif user_throw == "paper" && @comp_throw == "scissors"
  		@status = :lose
  	else
  		@status = :tie
  	end
  end


end

games_on_rails/app/controllers/secret_numbers_controller.rb
# secret_numbers_controller.rb

class SecretNumbersController < ApplicationController

	def new
	end

	def show
		@chosen_number = params[:id].to_i
		@secret_number = rand(5) + 1
	end

end

games_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GamesOnRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

games_on_rails/app/views/rock_paper_scissors/new.html.erb
<h1>Rock, Paper, Scissors</h1>

<%= link_to image_tag("rock_paper_scissors/paper.jpeg"), rock_paper_scissor_path(0) %>
<%= link_to image_tag("rock_paper_scissors/rock.jpeg"), rock_paper_scissor_path(1) %>
<%= link_to image_tag("rock_paper_scissors/scissors.jpeg"), rock_paper_scissor_path(2) %>

games_on_rails/app/views/rock_paper_scissors/show.html.erb
<h1>SHOW</h1>

<!--Comp chooses rock:
if user chooses rock -> tie
if user chooses paper -> user wins
if user chooses scissors -> user loses -->

      <h2>You threw:</h2>
      <%=image_tag "rock_paper_scissors/#{@user_throw}.jpeg" %>
      <h2><%=@user_throw.upcase%></h2>

<% if @status == :win %>
  <h1>CONGRATS! YOU WIN!</h1>
  <%= image_tag "games/winner.gif" %>
<% elsif @status == :tie %>
  <h1>It's a tie!</h2>
  <%= image_tag "games/tie.jpg" %>
<% else %>
  <h1>Sorry, you lose...</h1>
  <%= image_tag "games/cat-always-wins.jpeg" %>
<% end %>


<%= link_to "Play again", new_rock_paper_scissor_path %>

games_on_rails/app/views/secret_numbers/new.html.erb
<h1>This is a new Secret Number Game.</h1>

<% (1..5).each do |number| %>
	<%= link_to image_tag("secret_numbers/#{number}.jpeg"), 
		secret_number_path(number) %>

<% end %>

games_on_rails/app/views/secret_numbers/show.html.erb
<% if @secret_number == @chosen_number %>
<h1> Congrats - you won! </h1>
<% else %>
<h1> Sorry, you lost </h1>
<p> Secret number was: <%= @secret_number %> </p>
<% end %>

<%= link_to "Play again", new_secret_number_path %>