rewsly/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'stories#index'

  resources :stories

  get 'stories/:id' => 'stories#show'

end

rewsly/app/models/story.rb
class Story < ActiveRecord::Base
	validates :title, :link, :category, presence: true


end

rewsly/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

rewsly/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

rewsly/app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	def new
		@story = Story.new
	end

	def show
		@story = Story.find(params[:id])
	end

	def index 
		@stories = Story.all
		@story = Story.new
	end

	def create
		@story = Story.new(story_params)
			if @story.save
				redirect_to @story
			else
				render 'new'
			end
		end
	end



	def update
			@story = Story.find(params[:id])
			@story.update story_params
			redirect_to @story
	end

	def edit
		@story = Story.find(params[:id])
	end

	def story_params
		params.require(:story).permit(:title, :link, :category)
	end

rewsly/app/helpers/application_helper.rb
module ApplicationHelper
end

rewsly/app/helpers/stories_helper.rb
module StoriesHelper
end

rewsly/app/views/stories/_form.html.erb
<h1>Create a new story </h1>

<%= form_for @story do |s| %>
	<fieldset>
		<div class ='fields'>
			<%= s.label :title %>
			<%= s.text_field :title %>
		</div>
		<div class ='fields'>
			<%= s.label :link %>
			<%= s.text_field :link %>
		</div>
		<div class ='fields'>
			<%= s.label :category %>
			<%= s.text_field :category %>
		</div>
	</fieldset>
	
	<%= s.submit %>

<% end %>	

rewsly/app/views/stories/index.html.erb
<h1>Welcome to Rewsly</h1>
<% @stories.each do |s| %>
<div>
<h4><%= link_to s.title, story_path(s.id) %></h4>
<p><%= s.category %></p>
<% end %>
</div>

<%= form_for @story do |s| %>
	<fieldset>
		<div class ='fields'>
			<%= s.label :title %>
			<%= s.text_field :title %>
		</div>
		<div class ='fields'>
			<%= s.label :link %>
			<%= s.text_field :link %>
		</div>
		<div class ='fields'>
			<%= s.label :category %>
			<%= s.text_field :category %>
		</div>
	</fieldset>
	
	<%= s.submit %>

<% end %>	

rewsly/app/views/stories/new.html.erb
<h1>Create a new story </h1>

<%= render 'form' %>

rewsly/app/views/stories/show.html.erb
<h1><%= link_to @story.title, @story.link %></h1>
<p><%= @story.category %></p>