ritly/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'urls#index'

  resources :urls, :only => [:create, :new, :show] #TODO: restrict this to just :create, :new and :show

  get '/:code', to: 'urls#redirectors'

  get '/:code/preview', to: 'urls#preview'

end

ritly/app/models/url.rb
class Url < ActiveRecord::Base
	validates :link, presence: true

end

ritly/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

ritly/app/controllers/urls_controller.rb
class UrlsController < ApplicationController

def index
	@urls = Url.all
	@url = Url.new
end

def show
	preview
end

def new
	@url = Url.new
end

def create
	@url = Url.new(url_params)
	@url.hash_code = SecureRandom.urlsafe_base64(8)
	@url.save
	if @url.save
		redirect_to @url
	else
		render 'new'
	end
end

def redirectors
	@url = Url.find_by hash_code: params[:code]
    if @url
      redirect_to @url.link
    else
      redirect_to root_path
    end
end

private

	def url_params
		params.require('url').permit(:link)
	end

def preview
    @url = Url.find_by hash_code: params[:code]
    unless @url
      redirect_to root_path
  	end
end
end

ritly/app/helpers/urls_helper.rb
module UrlsHelper
end

ritly/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
<p>Logged in as <%= current_user.email %></p>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign Up", new_user_registration_path %> | <%=
link_to "Login", new_user_session_path %>

<% end %>


<%= yield %>

</body>
</html>

ritly/app/views/urls/_form.html.erb
<%= form_for @url do |f| %>
	<fieldset>
		<div class ='fields'>
			<%= f.label :link %>
			<%= f.text_field :link %>
		</div>
	</fieldset>
	
	<%= f.submit %>

<% end %>	

ritly/app/views/urls/_list.html.erb
<% @urls.each do |url| %>
	<div>
		<h3><%= link_to url.link, url_path(url.id) %></h3>
		<p><%= url.created_at %></p>
	</div>
<% end %>

<br/>

ritly/app/views/urls/index.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Ritly</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<h4>Please input a url to be shortened</h4>

<%= render "form" %>

<%= render "list" %>

ritly/app/views/urls/new.html.erb
<h1>Create a new Ritly Link</h1>

<%= render 'form' %>

ritly/app/views/urls/redirectors.html.erb
<h1>Ritly Redirect</h1>
<h4><%= "Link name: " @url.link %></h4>
<h4><%= "Ritly link: " @url.hash_code %></h4>
<p><%= @url.created_at %></p>

ritly/app/views/urls/show.html.erb
<h1>Your url hash for <%= @url.link %> is <%= @url.hash_code %> </h1>

<p>You can direct users to this Ritly URL: <%= link_to @full_path %></p>

<p>The Ritly URL will redirect them to: <%= link_to @url.link, @url.link %></p>