shirts_app/config/routes.rb
ShirtsApp::Application.routes.draw do

  root 'shirts#index'
  resources :shirts

  

end

shirts_app/app/models/shirt.rb
class Shirt < ActiveRecord::Base

def self.search_for(query)
	where('name LIKE :query OR description LIKE :query', query:"%#{query}%")
end

end

shirts_app/app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
	def index
  		@shirts = Shirt.search_for(params[:q])
  	end

	def show
		@shirt = Shirt.find(params[:id])
	end

	def new
		@shirt = Shirt.new
	end

	def create
		@shirt = Shirt.new(shirt_params)
		if @shirt.save
			redirect_to @shirt
		else
			render 'new'
		end
	end

	def update
		@shirt = Shirt.find(params[:id])
		@shirt.update shirt_params
		redirect_to @shirt
	end

	def edit
		@shirt = Shirt.find(params[:id])
	end

	private
		def shirt_params
			params.require('shirt').permit(:name, :description, :image)
		end

end

shirts_app/app/helpers/shirts_helper.rb
module ShirtsHelper
end

shirts_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShirtsApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

shirts_app/app/views/shirts/_form.html.erb
<%= form_for @shirt do |f| %>
	<fieldset>
		<div class ='fields'>
			<%= f.label :name %>
			<%= f.text_field :name %>
		</div>
		<div class ='fields'>
			<%= f.label :description %>
			<%= f.text_field :description %>
		</div>
		<div class ='fields'>
			<%= f.label :image %>
			<%= f.text_field :image %>
		</div>
	</fieldset>
	
	<%= f.submit %>

<% end %>	

shirts_app/app/views/shirts/_list.html.erb
<% @shirts.each do |shirt| %>
	<div>
		<h3><%= link_to shirt.name, shirt_path(shirt.id) %></h3>
		<p><%= shirt.description %></p>
		<p><%= image_tag "shirts/"+shirt.image %></p>
	</div>
<% end %>

<br/>

shirts_app/app/views/shirts/edit.html.erb
<h1>Edit shirt</h1>

<%= render 'form' %>

shirts_app/app/views/shirts/form.html.erb
<%= form_for @shirt do |f| %>
	<fieldset>
		<div class ='fields'>
			<% f.label :name %>
			<% f.text_field :name %>
		</div>
		<div class ='fields'>
			<% f.label :description %>
			<% f.text_field :description %>
		</div>
		<div class ='fields'>
			<% f.label :image %>
			<% f.text_field :image %>
		</div>
	</fieldset>
	<%= f.submit %>
<% end %>

shirts_app/app/views/shirts/index.html.erb
<h1>welcome to find my shirt</h1>

<h3><%= link_to "Add new shirt", new_shirt_path %></h3>

<%= form_tag "/", method: "GET" do %>
	<%= text_field_tag :q %>
	<%= submit_tag "Search" %>
<% end %>

<%= render "list" %>

shirts_app/app/views/shirts/new.html.erb
<h1>Create a new shirt </h1>

<%= render 'form' %>

shirts_app/app/views/shirts/show.html.erb
<h1><%= @shirt.name %></h1>
<p><%= @shirt.description %></p>
<%= image_tag "shirts/" + @shirt.image %>

<%= link_to "Edit", edit_shirt_path(@shirt) %>